#pragma once

#define CPROFILE_USDF_PlAYER_CAPSULE TEXT("USDFPlayerCapsule")
#define CPROFILE_USDF_PlAYER_CHARACTERMESH TEXT("USDFPlayerCharacterMesh")
#define CPROFILE_USDF_NONPLAYER_CAPSULE TEXT("USDFNonPlayerCapsule")
#define CPROFILE_USDF_NONPlAYER_CHARACTERMESH TEXT("USDFNonPlayerCharacterMesh")
#define CPROFILE_USDFTRIGGER TEXT("USDFTrigger")
#define CCHANNEL_USDF_PLAYERACTION ECC_GameTraceChannel1
#define CCHANNEL_USDF_NONPLAYERACTION ECC_GameTraceChannel4
